### ISSUE TITLE
APK availability outside playstore

### ISSUE THREAD

**Issue by emanuelb** [MohGovIL/Ramzor#10]
it's possible to obtain the APK for ramzor app only from GooglePlay which limit it to devices that have PlayStore app preinstalled, some ROMs (for example: https://grapheneos.org/) & devices don't contain this app, some won't use alternatives like AuroraStore, please add direct download option for universal-APK (contain all supported arch, arm/x86..), so users can install the app from official place (to avoid using sites such as apkpure.com etc..)
see related issue in Hamgaen app:
https://github.com/MohGovIL/hamagen-react-native/issues/72
Hamagen added APK & IPA file for each release on github in assets to download:
https://github.com/MohGovIL/hamagen-react-native/releases

**Comment by BarYamin** [comment]
You can simple use sites such as [APKPure](https://www.apkpure.com) that allow you to download the APK.

**Comment by TheYarin** [comment]
That's a good idea, and shouldn't be too difficult.

@BarYamin It's important to download software only from a trusted source. Downloading the APK from MOH's official site or from this GitHub repo would be a trusted alternative to 3rd party Play Store mirrors.

**Comment by BarYamin** [comment]
@TheYarin
APKPure is a very trust-worthy website that has been tested and verified.

**Comment by TheYarin** [comment]
@svetamorag Is the APK available for download from a trusted source?
