### ISSUE TITLE
Publish test vectors for signature verification

### ISSUE THREAD

**Issue by yuvadm** [MohGovIL/Ramzor#16]
There seems to be no published test vectors for the specification described in this repository.

This means community developers are limited in their ability to test their implementations against the spec, and must resolve to testing on their own data which includes PII. Such private data naturally cannot be published publicly, for example in the case of unit tests. 

It would be greatly beneficial to publish at least some test vectors for the most common payloads types that might be encountered in real-life scenarios.

**Comment by svetamorag** [comment]
You can find sample certificates in the "Verification" folder and get a payload using any QR scanner app.
I have added a payload sample as a text file as well:
https://github.com/MohGovIL/Ramzor/blob/main/Verification/ECDSA/Sample%20data/Sample-VacCertificate1-Payload.txt
