### ISSUE TITLE
Why insecure md5 is used for UVCI Composition?

### ISSUE THREAD

**Issue by emanuelb** [MohGovIL/Ramzor#6]
From UVCI Composition:
> The Unique string calculated as MD-5 hash function based on data fields from MoH“CoVID-19 Vaccination Record”. The subject is organized into a single plaintext string as follows:
MD5=([PII Information][Valid until date])
UVCI = [01]/[IL]/MD5{[PII Information][Valid until date]}#[crc32]

MD5 algorithm is old and insecure:
collisions:
https://github.com/corkami/collisions
and also vulnerable to length extension attack.

why is it used in this context? and not other algorithm for hashing? what the requirements are for the hash used in this case? and why md5 was chosen?

**Comment by svetamorag** [comment]
The data inside the UVCI is not a secret. We believe that MD5 is secured enough for public data.

**Comment by svetamorag** [comment]
UVCI was designed based on EU guidelines. Please see page 10 of this document: https://ec.europa.eu/health/sites/health/files/ehealth/docs/vaccination-proof_interoperability-guidelines_en.pdf

**Comment by emanuelb** [comment]
The problem with md5 is that it's a "cryptographic" but broken hash function, thus it's usage is discouraged, it's not secure for almost any usage, and should not be used for new developments.
if cryptographic hash function is needed, There are algorithms who are both safe & much faster then md5 like BLAKE2 or BLAKE3.
Both BLAKE functions support variable-length output.
if non cryptographic hash function is needed, there are still many choices which are better then md5...
