### ISSUE TITLE
[UX] Please consider removing the intro animation

### ISSUE THREAD

**Issue by kaminskypavel** [MohGovIL/Ramzor#8]
why should you consider it?

1. it has a bad resolution and aspect ratio 
2. it's super long... ~10 / 15m seconds. I'm not sure whether you're using that time to load remote data, but this is not the way to go...
3. 2001 is over.. let's keep it that way. we do not use "audio clips", "midi sounds" or "intro animations".

the app itself is gorgeous and well designed, it a shame that such a horrendous animation is ruining its overall UI experience

**Comment by RachelMendelovich** [comment]
Truth to be told, I really liked it :) 
Having said that, MoH have received that feedback from multiple users so are going to shorten it significantly. 
Thanks for taking the time to send this and please keep reviewing so the app can be improved.

**Comment by emanuelb** [comment]
Please open-source the source-code of the app (Android & iOS) so more people would review the code and the app will be improved!
>  Thanks for taking the time to send this and please keep reviewing so the app can be improved.

**Comment by svetamorag** [comment]
The App can't be an open-source project because of some policy restrictions.
